import {
  type LucideProps,
  Eye,
  EyeOff,
  Cpu,
  Stethoscope,
  Building2,
  HandCoins,
  HeartHandshake,
  ScanLine,
  ScanEye,
  Trophy,
  Activity,
  CircleDashed,
  Scissors,
  Zap,
  Syringe,
  Sparkles,
  Gauge,
  Target,
  CircleDot,
  Baby,
  Shield,
  ShieldCheck,
  Flame,
  Phone,
  Mail,
  MapPin,
  Clock,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ArrowRight,
  ArrowUpRight,
  Star,
  Quote,
  Check,
  CheckCircle2,
  Calendar,
  MessageCircle,
  Send,
  Award,
  Users,
  Microscope,
  Sparkle,
  Plus,
  Minus,
  ChevronsUp,
  GraduationCap,
  Building,
  HeartPulse,
  BadgeCheck,
  Video,
  Play,
  MoveRight,
  ClipboardList,
  FlaskConical,
  Glasses,
  ScanFace,
  Anchor,
} from "lucide-react";

const iconMap = {
  eye: Eye,
  "eye-off": EyeOff,
  cpu: Cpu,
  stethoscope: Stethoscope,
  "building-2": Building2,
  building: Building,
  "hand-coins": HandCoins,
  "heart-handshake": HeartHandshake,
  "scan-line": ScanLine,
  "scan-eye": ScanEye,
  trophy: Trophy,
  activity: Activity,
  "circle-dashed": CircleDashed,
  scissors: Scissors,
  zap: Zap,
  syringe: Syringe,
  sparkles: Sparkles,
  sparkle: Sparkle,
  gauge: Gauge,
  target: Target,
  "circle-dot": CircleDot,
  baby: Baby,
  shield: Shield,
  "shield-check": ShieldCheck,
  flame: Flame,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  clock: Clock,
  menu: Menu,
  x: X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "move-right": MoveRight,
  star: Star,
  quote: Quote,
  check: Check,
  "check-circle": CheckCircle2,
  calendar: Calendar,
  "message-circle": MessageCircle,
  send: Send,
  award: Award,
  users: Users,
  microscope: Microscope,
  plus: Plus,
  minus: Minus,
  "chevrons-up": ChevronsUp,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  "badge-check": BadgeCheck,
  video: Video,
  play: Play,
  "clipboard-list": ClipboardList,
  "flask-conical": FlaskConical,
  glasses: Glasses,
  "scan-face": ScanFace,
  anchor: Anchor,
} as const;

export type IconName = keyof typeof iconMap;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = iconMap[name as IconName];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
